### PR TITLE
Implement CI

### LINKED ISSUE #13: Add detekt to detec(k)t Kotlin code style
Use this cool tool to detekt code quality: https://github.com/arturbosch/detekt
Would assign that to me but I am no longer a collaborator

### PR DESCRIPTION
**Pull request by DRSchlaubi**
Fixes #13, #14

### CODE REVIEW

**Review by Quillraven — CHANGES_REQUESTED** [review]
I don't know if this is already the final version but if it is then please check the formatting.

Seems like it has a different formatting then the standard Kotlin format of Intellij which is bad especially for the git history if the entire project has changes which are only different whitespaces/tabs.

If this is not the final version then ignore my comment ;)

**Comment by DRSchlaubi** [comment]
You noticed this is a draft, right? https://rice.by.devs-from.asia/chrome_TjCjISRJJF.png
also what I don't know what you mean this is the default formatting

**Comment by Quillraven** [comment]
Shall we close this request, as detekt is now in place and we also have a github workflow available?

**Comment by Quillraven** [comment]
Release version 1 today. Will close this PR for now since there was no progress in the last months and I am quite happy with what we achieved with detekt and the github workflow.

Thanks again for the help!

**Pull request closed without merging**
